# Generated by Django 4.0.4 on 2022-05-25 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ex', '0002_tipday_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipday',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='tipday',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_tips', to=settings.AUTH_USER_MODEL),
        ),
    ]
