# Generated by Django 4.0.4 on 2022-05-25 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ex', '0003_alter_tipday_options_tipday_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipday',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_tips', to=settings.AUTH_USER_MODEL),
        ),
    ]
